//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Punchout.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class CI_Item
    {
        public string ItemCode { get; set; }
        public string ItemType { get; set; }
        public string ItemCodeDesc { get; set; }
        public string ExtendedDescriptionKey { get; set; }
        public string UseInAR { get; set; }
        public string UseInSO { get; set; }
        public string UseInPO { get; set; }
        public string UseInBM { get; set; }
        public string CalculateCommission { get; set; }
        public string DropShip { get; set; }
        public string EBMEnabled { get; set; }
        public string PriceCode { get; set; }
        public string PrintReceiptLabels { get; set; }
        public string AllocateLandedCost { get; set; }
        public string WarrantyCode { get; set; }
        public string SalesUnitOfMeasure { get; set; }
        public string PurchaseUnitOfMeasure { get; set; }
        public string StandardUnitOfMeasure { get; set; }
        public string PostToGLByDivision { get; set; }
        public string SalesAcctKey { get; set; }
        public string CostOfGoodsSoldAcctKey { get; set; }
        public string InventoryAcctKey { get; set; }
        public string PurchaseAcctKey { get; set; }
        public string ManufacturingCostAcctKey { get; set; }
        public string TaxClass { get; set; }
        public string PurchasesTaxClass { get; set; }
        public string ProductLine { get; set; }
        public string ProductType { get; set; }
        public string Valuation { get; set; }
        public string DefaultWarehouseCode { get; set; }
        public string PrimaryAPDivisionNo { get; set; }
        public string PrimaryVendorNo { get; set; }
        public string ImageFile { get; set; }
        public string Category1 { get; set; }
        public string Category2 { get; set; }
        public string Category3 { get; set; }
        public string Category4 { get; set; }
        public string ExplodeKitItems { get; set; }
        public string ShipWeight { get; set; }
        public string CommentText { get; set; }
        public string RestockingMethod { get; set; }
        public Nullable<decimal> StandardUnitCost { get; set; }
        public Nullable<decimal> StandardUnitPrice { get; set; }
        public Nullable<decimal> CommissionRate { get; set; }
        public Nullable<decimal> BaseCommAmt { get; set; }
        public Nullable<decimal> PurchaseUMConvFctr { get; set; }
        public Nullable<decimal> SalesUMConvFctr { get; set; }
        public Nullable<decimal> Volume { get; set; }
        public Nullable<decimal> RestockingCharge { get; set; }
        public string ProcurementType { get; set; }
        public System.DateTime DateCreated { get; set; }
        public string TimeCreated { get; set; }
        public string UserCreatedKey { get; set; }
        public System.DateTime DateUpdated { get; set; }
        public string TimeUpdated { get; set; }
        public string UserUpdatedKey { get; set; }
        public string UDF_CATEGORY { get; set; }
        public string UDF_EPA_CONTAINER { get; set; }
        public string UDF_EPA_ITEM { get; set; }
        public string UDF_EPA_PHASE { get; set; }
        public string UDF_EPA_PRESSURE { get; set; }
        public string UDF_EPA_TEMP { get; set; }
        public string UDF_MANUFACT { get; set; }
        public string UDF_PRD_CATEGORY { get; set; }
        public string UDF_CHEM_CATEGORY { get; set; }
        public string UDF_COST_CENTER { get; set; }
        public string UDF_PROCESS { get; set; }
        public string UDF_GMR2_STORAGE { get; set; }
        public string UDF_GMR2_TEMP { get; set; }
        public string UDF_GMR2_PRESSURE1 { get; set; }
        public string UDF_EPA_CONVERSION_UNIT { get; set; }
        public string UDF_WTC_MATERIALS_BREAKDOWN { get; set; }
        public string UDF_BEG_DATE { get; set; }
        public string UDF_END_DATE { get; set; }
        public string UDF_CHEMPAX { get; set; }
        public string UDF_LDT { get; set; }
        public string UDF_LDTLGR { get; set; }
        public string UDF_CCN { get; set; }
        public string UDF_MFG_PART { get; set; }
        public string AllowBackOrders { get; set; }
        public string AllowReturns { get; set; }
        public string AllowTradeDiscount { get; set; }
        public string ConfirmCostIncrInRcptOfGoods { get; set; }
        public System.DateTime LastSoldDate { get; set; }
        public System.DateTime LastReceiptDate { get; set; }
        public string SalesPromotionCode { get; set; }
        public System.DateTime SaleStartingDate { get; set; }
        public System.DateTime SaleEndingDate { get; set; }
        public string SaleMethod { get; set; }
        public string NextLotSerialNo { get; set; }
        public string InventoryCycle { get; set; }
        public string RoutingNo { get; set; }
        public string PlannerCode { get; set; }
        public string BuyerCode { get; set; }
        public string LowLevelCode { get; set; }
        public string PlannedByMRP { get; set; }
        public string VendorItemCode { get; set; }
        public string SetupCharge { get; set; }
        public string AttachmentFileName { get; set; }
        public Nullable<decimal> ItemImageWidthInPixels { get; set; }
        public Nullable<decimal> ItemImageHeightInPixels { get; set; }
        public Nullable<decimal> LastTotalUnitCost { get; set; }
        public Nullable<decimal> AverageUnitCost { get; set; }
        public Nullable<decimal> SalesPromotionPrice { get; set; }
        public Nullable<decimal> SuggestedRetailPrice { get; set; }
        public Nullable<decimal> SalesPromotionDiscountPercent { get; set; }
        public Nullable<decimal> TotalQuantityOnHand { get; set; }
        public Nullable<decimal> AverageBackOrderFillDays { get; set; }
        public Nullable<decimal> LastAllocatedUnitCost { get; set; }
        public Nullable<decimal> TotalInventoryValue { get; set; }
        public string UDF_HNW_CAS { get; set; }
        public string UDF_HNW_CLASSIFICATION_CODE { get; set; }
        public string UDF_HNW_CONTENT_QTY_PER_UNIT { get; set; }
        public string UDF_HNW_HARMONIZED_TARIFF_CODE { get; set; }
        public string UDF_HNW_ITEM_STATUS { get; set; }
        public string UDF_HNW_MANUF_COUNTRY_OF_ORIG { get; set; }
        public string UDF_HNW_MINIMUM_ORDER_QUANTITY { get; set; }
        public string UDF_HNW_PACKAGING_UOM { get; set; }
        public string UDF_HNW_SHELF_LIFE { get; set; }
        public string UDF_HNW_UOM_OF_WEIGHT { get; set; }
        public string UDF_HNW_WEIGHT_OF_PRODUCT { get; set; }
        public string UDF_HNW_SPECIAL_TREATMENT_CLAS { get; set; }
        public string UDF_GMR2_CONVERSION_FACTOR { get; set; }
        public string UDF_GMR2_COST_CENTER_CLASSIFIC { get; set; }
        public string UDF_GMR2_PLANT_ID { get; set; }
        public string UDF_MISC_PROD_LINE { get; set; }
        public string InactiveItem { get; set; }
        public string UDF_PROD_GROUP_KEY { get; set; }
        public string UDF_PROD_GROUP_MAIN { get; set; }
        public string UDF_PROD_GROUP_SUB { get; set; }
        public string UDF_CHRYSLER_PRODUCT_TYPE { get; set; }
        public string UDF_ITDI { get; set; }
        public string UDF_HNW_PROD_CATEGORY { get; set; }
        public string UDF_ERG_NUMBER { get; set; }
        public string UDF_HAZARD_CLASS_1 { get; set; }
        public string UDF_HAZARD_CLASS_2 { get; set; }
        public string UDF_PACKING_GROUP { get; set; }
        public string UDF_PROPER_SHIPPING_NAME { get; set; }
        public string UDF_UN_NUMBER { get; set; }
        public System.DateTime LastPhysicalCountDate { get; set; }
        public string UDF_CAGE_CODE { get; set; }
        public string UDF_HCC { get; set; }
        public Nullable<decimal> UDF_TC_PACK_QTY { get; set; }
        public Nullable<decimal> UDF_MARKUP { get; set; }
        public string CommodityCode { get; set; }
        public string UDF_CLAVEPRODSERV { get; set; }
        public string UDF_CLAVEUNIDAD { get; set; }
        public string UDF_SO_CLAVEPRODSERV { get; set; }
        public string UDF_SO_CLAVEUNIDAD { get; set; }
    }
}
